name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test > test-results.txt 2>&1 || true # Capture output, continue on failure

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-results.txt

  deploy:
    needs: test # Depends on test job
    runs-on: [self-hosted] # Self-hosted runner (Windows)
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Download test results
        uses: actions/download-artifact@v4
        with:
          name: test-results
          path: .\artifacts # Windows-style path

      - name: Display test results
        run: type .\artifacts\test-results.txt # 'type' for Windows instead of 'cat'

      - name: Deploy application
        run: |
          npm install -g pm2
          pm2 delete node-app || true
          pm2 start "npm start" --name="node-app"
          pm2 save
